name: artifact
on: push

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        uses: echo hello-world > hello.txt
      - name: upload artifact
        uses: action/upload-artifact@v3
        with:
          name: artifact-text
          paths: ./hello.txt

  download-artifact:
    runs-on: ubuntu-latest
    needs: [upload-artifact]
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-text
          path: ./
      - name: check
        run: cat hello.txt

