name: output
on: push

jobs:
  create-output:
    runs-on: ubuntu-latest
    steps:
      - name: echo output
        id: check-output
        run: |
          echo "test=hello" >> $GITHUB_OUTPUT
      - name: name check
        run: |
          echo ${{ steps.check-output.outputs.test }}
