name: output
on: push

jobs:
  create-output:
    runs-on: ubuntu-latest
    outputs:
      mykey: ${{ steps.check-output.outputs.mykey }}
    steps:
      - name: echo output
        id: check-output
        run: |
          echo "mykey=hello" >> $GITHUB_OUTPUT
      - name: name check
        run: |
          echo ${{ steps.check-output.outputs.mykey }}

  get-output:
    runs-on: ubuntu-latest
    needs: [create-output]
    steps:
      - name: get output
        run: |
          echo ${{ needs.create-output.outputs.mykey }}
